// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamPerformancePredictor.Data;

#nullable disable

namespace TeamPerformancePredictor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315054731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamPerformancePredictor.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("DeadlinesMissed")
                        .HasColumnType("real");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<float>("HoursWorked")
                        .HasColumnType("real");

                    b.Property<float>("LeaveDaysTaken")
                        .HasColumnType("real");

                    b.Property<float>("MeetingsAttended")
                        .HasColumnType("real");

                    b.Property<float>("OvertimeHours")
                        .HasColumnType("real");

                    b.Property<float>("PeerCollaborationScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("TasksCompleted")
                        .HasColumnType("real");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ActivityLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeadlinesMissed = 0f,
                            EmployeeId = 1,
                            HoursWorked = 40f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 5f,
                            RecordedAt = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 12f,
                            WeekStartDate = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DeadlinesMissed = 0f,
                            EmployeeId = 1,
                            HoursWorked = 42f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 6f,
                            OvertimeHours = 3f,
                            PeerCollaborationScore = 5f,
                            RecordedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 14f,
                            WeekStartDate = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DeadlinesMissed = 0f,
                            EmployeeId = 1,
                            HoursWorked = 38f,
                            LeaveDaysTaken = 1f,
                            MeetingsAttended = 4f,
                            OvertimeHours = 1f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 11f,
                            WeekStartDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DeadlinesMissed = 0f,
                            EmployeeId = 1,
                            HoursWorked = 41f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 5f,
                            RecordedAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 13f,
                            WeekStartDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DeadlinesMissed = 0f,
                            EmployeeId = 1,
                            HoursWorked = 43f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 6f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 5f,
                            RecordedAt = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 15f,
                            WeekStartDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            DeadlinesMissed = 0f,
                            EmployeeId = 1,
                            HoursWorked = 40f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 12f,
                            WeekStartDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            DeadlinesMissed = 1f,
                            EmployeeId = 2,
                            HoursWorked = 50f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 7f,
                            OvertimeHours = 10f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 9f,
                            WeekStartDate = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            DeadlinesMissed = 2f,
                            EmployeeId = 2,
                            HoursWorked = 55f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 8f,
                            OvertimeHours = 15f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 8f,
                            WeekStartDate = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            DeadlinesMissed = 2f,
                            EmployeeId = 2,
                            HoursWorked = 60f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 9f,
                            OvertimeHours = 18f,
                            PeerCollaborationScore = 2f,
                            RecordedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 7f,
                            WeekStartDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            DeadlinesMissed = 3f,
                            EmployeeId = 2,
                            HoursWorked = 62f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 8f,
                            OvertimeHours = 20f,
                            PeerCollaborationScore = 2f,
                            RecordedAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 6f,
                            WeekStartDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            DeadlinesMissed = 3f,
                            EmployeeId = 2,
                            HoursWorked = 65f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 7f,
                            OvertimeHours = 22f,
                            PeerCollaborationScore = 2f,
                            RecordedAt = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 5f,
                            WeekStartDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            DeadlinesMissed = 4f,
                            EmployeeId = 2,
                            HoursWorked = 68f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 6f,
                            OvertimeHours = 25f,
                            PeerCollaborationScore = 1f,
                            RecordedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 4f,
                            WeekStartDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            DeadlinesMissed = 1f,
                            EmployeeId = 3,
                            HoursWorked = 30f,
                            LeaveDaysTaken = 2f,
                            MeetingsAttended = 3f,
                            OvertimeHours = 0f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 4f,
                            WeekStartDate = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            DeadlinesMissed = 2f,
                            EmployeeId = 3,
                            HoursWorked = 25f,
                            LeaveDaysTaken = 3f,
                            MeetingsAttended = 2f,
                            OvertimeHours = 0f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 3f,
                            WeekStartDate = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            DeadlinesMissed = 1f,
                            EmployeeId = 3,
                            HoursWorked = 20f,
                            LeaveDaysTaken = 2f,
                            MeetingsAttended = 2f,
                            OvertimeHours = 0f,
                            PeerCollaborationScore = 2f,
                            RecordedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 2f,
                            WeekStartDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            DeadlinesMissed = 2f,
                            EmployeeId = 3,
                            HoursWorked = 22f,
                            LeaveDaysTaken = 3f,
                            MeetingsAttended = 2f,
                            OvertimeHours = 0f,
                            PeerCollaborationScore = 2f,
                            RecordedAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 3f,
                            WeekStartDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            DeadlinesMissed = 2f,
                            EmployeeId = 3,
                            HoursWorked = 18f,
                            LeaveDaysTaken = 2f,
                            MeetingsAttended = 1f,
                            OvertimeHours = 0f,
                            PeerCollaborationScore = 2f,
                            RecordedAt = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 2f,
                            WeekStartDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            DeadlinesMissed = 1f,
                            EmployeeId = 3,
                            HoursWorked = 20f,
                            LeaveDaysTaken = 2f,
                            MeetingsAttended = 2f,
                            OvertimeHours = 0f,
                            PeerCollaborationScore = 2f,
                            RecordedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 2f,
                            WeekStartDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            DeadlinesMissed = 0f,
                            EmployeeId = 4,
                            HoursWorked = 40f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 4f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 8f,
                            WeekStartDate = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            DeadlinesMissed = 0f,
                            EmployeeId = 4,
                            HoursWorked = 42f,
                            LeaveDaysTaken = 1f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 5f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 9f,
                            WeekStartDate = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            DeadlinesMissed = 0f,
                            EmployeeId = 4,
                            HoursWorked = 41f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 4f,
                            OvertimeHours = 4f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 8f,
                            WeekStartDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            DeadlinesMissed = 1f,
                            EmployeeId = 4,
                            HoursWorked = 40f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 4f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 9f,
                            WeekStartDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            DeadlinesMissed = 0f,
                            EmployeeId = 4,
                            HoursWorked = 42f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 5f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 8f,
                            WeekStartDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            DeadlinesMissed = 0f,
                            EmployeeId = 4,
                            HoursWorked = 41f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 4f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 9f,
                            WeekStartDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            DeadlinesMissed = 2f,
                            EmployeeId = 5,
                            HoursWorked = 32f,
                            LeaveDaysTaken = 2f,
                            MeetingsAttended = 3f,
                            OvertimeHours = 1f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 5f,
                            WeekStartDate = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            DeadlinesMissed = 1f,
                            EmployeeId = 5,
                            HoursWorked = 35f,
                            LeaveDaysTaken = 1f,
                            MeetingsAttended = 4f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 7f,
                            WeekStartDate = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            DeadlinesMissed = 1f,
                            EmployeeId = 5,
                            HoursWorked = 38f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 4f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 9f,
                            WeekStartDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            DeadlinesMissed = 0f,
                            EmployeeId = 5,
                            HoursWorked = 40f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 10f,
                            WeekStartDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            DeadlinesMissed = 0f,
                            EmployeeId = 5,
                            HoursWorked = 41f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 11f,
                            WeekStartDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            DeadlinesMissed = 0f,
                            EmployeeId = 5,
                            HoursWorked = 42f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 6f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 5f,
                            RecordedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 12f,
                            WeekStartDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            DeadlinesMissed = 1f,
                            EmployeeId = 6,
                            HoursWorked = 45f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 6f,
                            OvertimeHours = 6f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 10f,
                            WeekStartDate = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            DeadlinesMissed = 1f,
                            EmployeeId = 6,
                            HoursWorked = 48f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 7f,
                            OvertimeHours = 8f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 9f,
                            WeekStartDate = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            DeadlinesMissed = 2f,
                            EmployeeId = 6,
                            HoursWorked = 50f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 7f,
                            OvertimeHours = 10f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 8f,
                            WeekStartDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            DeadlinesMissed = 2f,
                            EmployeeId = 6,
                            HoursWorked = 52f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 6f,
                            OvertimeHours = 12f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 8f,
                            WeekStartDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            DeadlinesMissed = 1f,
                            EmployeeId = 6,
                            HoursWorked = 50f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 7f,
                            OvertimeHours = 10f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 9f,
                            WeekStartDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            DeadlinesMissed = 2f,
                            EmployeeId = 6,
                            HoursWorked = 51f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 6f,
                            OvertimeHours = 11f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 8f,
                            WeekStartDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            DeadlinesMissed = 0f,
                            EmployeeId = 7,
                            HoursWorked = 40f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 7f,
                            OvertimeHours = 1f,
                            PeerCollaborationScore = 5f,
                            RecordedAt = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 13f,
                            WeekStartDate = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            DeadlinesMissed = 0f,
                            EmployeeId = 7,
                            HoursWorked = 42f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 7f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 5f,
                            RecordedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 15f,
                            WeekStartDate = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            DeadlinesMissed = 0f,
                            EmployeeId = 7,
                            HoursWorked = 41f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 6f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 5f,
                            RecordedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 14f,
                            WeekStartDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            DeadlinesMissed = 0f,
                            EmployeeId = 7,
                            HoursWorked = 40f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 7f,
                            OvertimeHours = 1f,
                            PeerCollaborationScore = 5f,
                            RecordedAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 13f,
                            WeekStartDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            DeadlinesMissed = 0f,
                            EmployeeId = 7,
                            HoursWorked = 43f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 8f,
                            OvertimeHours = 2f,
                            PeerCollaborationScore = 5f,
                            RecordedAt = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 16f,
                            WeekStartDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            DeadlinesMissed = 0f,
                            EmployeeId = 7,
                            HoursWorked = 41f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 7f,
                            OvertimeHours = 1f,
                            PeerCollaborationScore = 5f,
                            RecordedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 14f,
                            WeekStartDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            DeadlinesMissed = 2f,
                            EmployeeId = 8,
                            HoursWorked = 38f,
                            LeaveDaysTaken = 1f,
                            MeetingsAttended = 4f,
                            OvertimeHours = 0f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 6f,
                            WeekStartDate = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            DeadlinesMissed = 2f,
                            EmployeeId = 8,
                            HoursWorked = 39f,
                            LeaveDaysTaken = 1f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 1f,
                            PeerCollaborationScore = 3f,
                            RecordedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 7f,
                            WeekStartDate = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            DeadlinesMissed = 1f,
                            EmployeeId = 8,
                            HoursWorked = 40f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 1f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 8f,
                            WeekStartDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            DeadlinesMissed = 1f,
                            EmployeeId = 8,
                            HoursWorked = 40f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 1f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 9f,
                            WeekStartDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            DeadlinesMissed = 0f,
                            EmployeeId = 8,
                            HoursWorked = 41f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 6f,
                            OvertimeHours = 1f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 10f,
                            WeekStartDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            DeadlinesMissed = 0f,
                            EmployeeId = 8,
                            HoursWorked = 40f,
                            LeaveDaysTaken = 0f,
                            MeetingsAttended = 5f,
                            OvertimeHours = 1f,
                            PeerCollaborationScore = 4f,
                            RecordedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksCompleted = 10f,
                            WeekStartDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TeamPerformancePredictor.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$pnbPjSTekE6DJg/ZH6ltjuSiEEodgvIFtOHMnFXwTk/pq./UFpZhy",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Rahul Sharma",
                            IsActive = true,
                            PasswordHash = "$2a$11$ht7TK9w.9c4Cwlt/vKuttuID9LICdqj9n15WahEFhtysUsB0cXn/a",
                            Role = "Manager",
                            Username = "manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Kavita Pillai",
                            IsActive = true,
                            PasswordHash = "$2a$11$naQMYK48RARy1qPSHkv6UuVsEM2Zz1K9NjXpky/7nVSviP4bp39Fm",
                            Role = "HR",
                            Username = "hr"
                        });
                });

            modelBuilder.Entity("TeamPerformancePredictor.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Technology",
                            Designation = "Senior Developer",
                            Email = "alice@company.com",
                            IsActive = true,
                            JoinDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Department = "Technology",
                            Designation = "Backend Developer",
                            Email = "bob@company.com",
                            IsActive = true,
                            JoinDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bob Smith",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Department = "Business",
                            Designation = "Marketing Analyst",
                            Email = "carol@company.com",
                            IsActive = true,
                            JoinDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Carol White",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            Department = "Business",
                            Designation = "Growth Manager",
                            Email = "david@company.com",
                            IsActive = true,
                            JoinDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "David Lee",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Department = "Technology",
                            Designation = "Data Scientist",
                            Email = "eva@company.com",
                            IsActive = true,
                            JoinDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eva Chen",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 6,
                            Department = "Technology",
                            Designation = "ML Engineer",
                            Email = "frank@company.com",
                            IsActive = true,
                            JoinDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Frank Miller",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 7,
                            Department = "Strategy",
                            Designation = "Product Manager",
                            Email = "grace@company.com",
                            IsActive = true,
                            JoinDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grace Kim",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 8,
                            Department = "Strategy",
                            Designation = "UX Researcher",
                            Email = "henry@company.com",
                            IsActive = true,
                            JoinDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Henry Brown",
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("TeamPerformancePredictor.Models.PredictionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BurnoutProbability")
                        .HasColumnType("real");

                    b.Property<string>("BurnoutRiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PredictionDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("ProductivityScore")
                        .HasColumnType("real");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PredictionResults");
                });

            modelBuilder.Entity("TeamPerformancePredictor.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Technology",
                            ManagerName = "Rahul Sharma",
                            TeamName = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Business",
                            ManagerName = "Priya Mehta",
                            TeamName = "Marketing"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Technology",
                            ManagerName = "Arjun Nair",
                            TeamName = "Data Science"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Strategy",
                            ManagerName = "Sneha Iyer",
                            TeamName = "Product"
                        });
                });

            modelBuilder.Entity("TeamPerformancePredictor.Models.ActivityLog", b =>
                {
                    b.HasOne("TeamPerformancePredictor.Models.Employee", "Employee")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TeamPerformancePredictor.Models.Employee", b =>
                {
                    b.HasOne("TeamPerformancePredictor.Models.Team", "Team")
                        .WithMany("Employees")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamPerformancePredictor.Models.PredictionResult", b =>
                {
                    b.HasOne("TeamPerformancePredictor.Models.Employee", "Employee")
                        .WithMany("PredictionResults")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TeamPerformancePredictor.Models.Employee", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("PredictionResults");
                });

            modelBuilder.Entity("TeamPerformancePredictor.Models.Team", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
